plugin_mixins:
    aws_service:
        class: AWSServiceMixin
        credentials: true
        option:
            region:
                type: str
                default: "us-east-1"
                help: "AWS service region"
                config_name: aws_region

    ssh_task:
        class: SSHTaskMixin
        requirement:
            servers: []
        option:
            filter: AND
