
_ansible: &ansible
  provider: ansible
  roles: server-admin
  config: ansible.cfg
  group_vars: variables


bootstrap:
  <<: *ansible
  playbooks: bootstrap.yml

password:
  <<: *ansible
  playbooks: password.yml

mount:
  <<: *ansible
  playbooks: mount.yml

user-environment:
  <<: *ansible
  playbooks: user-environment.yml
