_ansible: &ansible
    provider: ansible
    roles: server-admin
    directory: ansible

password:
    <<: *ansible
    playbooks: password.yml

mount:
    <<: *ansible
    playbooks: mount.yml

user-environment:
    <<: *ansible
    playbooks: user-environment.yml
