
bootstrap:
  provider: remote_script
  module: core
  script: scripts/bootstrap.sh
  roles: server-admin
  sudo: true
  args:
    - "@user"
    - /var/log/bootstrap.log
    - "@dev_build"
    - "@timezone"
  options:
    user: ubuntu
    dev_build: false
    timezone: America/New_York

bootstrap-log:
  provider: remote_command
  command: cat /var/log/bootstrap.log
  roles: server-admin
  sudo: true

update:
  provider: remote_command
  command: docker-compose pull && docker-compose up -d
  roles: server-admin

restart:
  provider: remote_command
  command: docker-compose restart @system
  roles: server-admin
  options:
    system: api

log:
  provider: remote_command
  command: docker-compose logs --tail=@count @system
  roles: server-admin
  options:
    count: 100
    system: api
