
_server: &server
  roles: server-admin


cli:
  <<: *server
  provider: remote_command
  command: "@command"
  options:
    command: env

sudo:
  <<: *server
  provider: remote_command
  command: "@command"
  sudo: true
  options:
    command: env
