
bootstrap:
  provider: remote_script
  module: core
  script: scripts/bootstrap.sh
  roles: server-admin
  sudo: true
  args:
    - "@user"
    - /var/log/bootstrap.log
    - "@dev_build"
    - "@timezone"
  options:
    dev_build: false
    timezone: America/New_York
