- name: install | utility packages
  apt:
      name: "{{ utility_packages }}"
      state: present
      update_cache: yes
  vars:
      utility_packages:
          - vim
          - git
          - sshpass
