---
- include: install.yml
- include: >
    mount.yml
    mount_type={{ item.type }}
    mount_path={{ item.path }}
    mount_source={{ item.source }}
    mount_options={{ item.options | default(omit) }}
    mount_dump={{ item.dump | default(omit) }}
    mount_passno={{ item.passno | default(omit) }}
    mount_owner={{ item.owner | default('root') }}
    mount_group={{ item.group | default('root') }}
    mount_mode={{ item.mode | default('0755') }}
  with_items: "{{ mounts }}"
