config:
  root_domain: example.com
  root_domain_email: test@example.com

  primary_timezone: America/New_York

  network_cidr_base: 10.0.0.0/8
  network_cidr_prefix: 16
  network_dns_support: True
  network_groups: core

  core_firewall_groups: core

  ssh_port: 22

  storage_firewalls:
    - internet
    - nfs

group:
  core:
