---
- name: service | stop cenv-application
  shell: docker-compose rm --stop --force
  become: yes
  become_user: "{{ app_user }}"
  when: _docker_compose.stat.exists == True
  args:
    chdir: "{{ app_home }}"

- name: service | docker-compose
  get_url:
    url: "{{ remote_docker_compose }}"
    dest: "{{ local_docker_compose }}"
    force: true
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0664"

- name: service | start cenv-application
  shell: docker-compose up -d
  become: yes
  become_user: "{{ app_user }}"
  args:
    chdir: "{{ app_home }}"
