parents:
  - config

config:
  aws_networks:
    - aws-us-east-1
    - aws-us-east-2
    - aws-us-west-1
    - aws-us-west-2
    - aws-ca-central-1
    - aws-sa-east-1
    - aws-eu-central-1
    - aws-eu-west-1
    - aws-eu-west-2
    - aws-eu-west-3
    - aws-ap-northeast-1
    - aws-ap-northeast-2
    - aws-ap-south-1
    - aws-ap-southeast-1
    - aws-ap-southeast-2

  aws_nat_subnets:
    - nat-a
    - nat-b
    - nat-c

  # Ubuntu 18.04LTS hvm:ebs-ssd
  aws_ubuntu_user: ubuntu
  aws_ubuntu_image:
    aws-us-east-1: ami-07073342279f98d28
    aws-us-east-2: ami-02e1499f8253f416f
    aws-us-west-1: ami-09a3ee98385ff6b68
    aws-us-west-2: ami-0e3e4660d8725dd31
    aws-ca-central-1: ami-00a7d7ec7a73de008
    aws-sa-east-1: ami-0100acce7c30020c9
    aws-eu-central-1: ami-015796b0bb7c85278
    aws-eu-west-1: ami-0c21eb76a5574aa2f
    aws-eu-west-2: ami-031e9af9a62a515ca
    aws-eu-west-3: ami-0cf799901ece2e2af
    aws-ap-northeast-1: ami-0238fc6af6bba5241
    aws-ap-northeast-2: ami-0a5732cf00ef2da99
    aws-ap-south-1: ami-0bcc667116a070e40
    aws-ap-southeast-1: ami-033a3bd1e8ea825a5
    aws-ap-southeast-2: ami-0626846f14dbd80e5

  aws_storage_performance_mode: generalPurpose
  aws_storage_throughput_mode: bursting
  aws_storage_provisioned_throughput: null
  aws_storage_encrypted: false

  aws_efs_volume_options:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport
