- hosts: all
  gather_facts: no
  tasks:
      - name: Update user password
        user:
            name: "{{ user }}"
            update_password: always
            password: "{{ password | password_hash('sha512') }}"
  vars:
      user: admin
      password: admin
